Simplify the code.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -17,19 +17,23 @@ jobs:
            uses: actions/checkout@v2
            with:
             fetch-depth: 0
-           env:
-             RELEASE_TAG: "${{ github.event.release.tag_name }}"
 
          - name: "Get package version"
            id: package-version
            uses: "martinbeentjes/npm-get-version-action@main"
 
-         - name: Fail if the tag release value is equivalent to the package.json version value
-           if: ${{ github.event.release.tag_name }} == ${{ steps.package-version.outputs.current-version }}
+         - name: "Compare the tag release value to the package.json version value, fail the workflow if the release is newer"
+           id: compare-version
+           shell: bash
            run: |
-             echo RELEASE_TAG =  ${{ github.event.release.tag_name }}
-             echo PACKAGE_VERSION =  ${{ steps.package-version.outputs.current-version }}
-             exit 1
+            if [ "$(printf '%s\n' "${{ steps.package-version.outputs.current-version }}" "${{ github.event.release.tag_name }}" | sort -V | head -n1)" = "${{ steps.package-version.outputs.current-version }}" ]; then
+                echo "ERROR"
+                exit 1
+            else
+                echo "OK"
+                exit 0
+            fi
+             echo "Comparing [${{ github.event.release.tag_name }}] to [${{ steps.package-version.outputs.current-version }}]"
 
          - uses: "marvinpinto/action-automatic-releases@latest"
            with:
@@ -37,3 +41,4 @@ jobs:
              repo_token: "${{ secrets.GITHUB_TOKEN }}"
              automatic_release_tag: ${{ steps.package-version.outputs.current-version}} 
              prerelease: false
+
