Test.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -22,28 +22,20 @@ jobs:
            id: package-version
            uses: "martinbeentjes/npm-get-version-action@main"
 
-         - name: Compare the tag release value to the package.json version value
+         - name: "Compare the tag release value to the package.json version value"""
            id: compare-version
            shell: bash
            run: |
-            vercompe() {
-                [  "$1" = "`echo -e "$1\n$2" | sort -V | head -n1`" ]
-            }
-            
-            vercomp() {
-                [ "$1" = "$2" ] && return 1 || vercompe $1 $2
-            }
-
-            echo "COMPARE_RESULT=$(vercomp ${{ github.event.release.tag_name }} ${{ steps.package-version.outputs.current-version }} && echo 1 || echo 0 )" >> $GITHUB_OUTPUT
-
+             echo "COMPARE_RESULT=$(./comp_ver.sh ${{ github.event.release.tag_name }} ${{ steps.package-version.outputs.current-version }})" >> $GITHUB_OUTPUT
+         
          - name: Fail if the tag release value is equivalent to the package.json version value
-           if: ${{ steps.compare-version.outputs.COMPARE_RESULT }} == "1"
+           if: steps.compare-version.outputs.COMPARE_RESULT == 'ERROR'
            shell: bash
            run: |
-             echo COMPARE_RESULT =  ${{ steps.compare-version.outputs.COMPARE_RESULT }}
-             echo RELEASE_TAG =  ${{ github.event.release.tag_name }}
-             echo PACKAGE_VERSION =  ${{ steps.package-version.outputs.current-version }}
-             exit 1
+             echo "FAILED"
+             echo ${{ steps.compare-version.outputs.COMPARE_RESULT }}
+              exit 1
+
 
          - uses: "marvinpinto/action-automatic-releases@latest"
            with:
